name: Crowdin pull and merge
on:
  workflow_dispatch:

jobs:
  pull:
    name: Pull translations from Crowdin
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v7
        with:
          ref: main
          fetch-depth: 0
          clean: true

      - name: Pull strings from Crowdin
        uses: crowdin/github-action@v2
        with:
          config: crowdin.yml
          upload_sources: false
          download_translations: true
          skip_ref_checkout: true
          localization_branch_name: crowdin
          create_pull_request: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

  merge:
    name: Squash merge Crowdin into main
    if: github.event_name == 'workflow_dispatch'
    needs: pull
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout crowdin branch
        uses: actions/checkout@v7
        with:
          ref: crowdin
          fetch-depth: 0
          clean: true

      - name: Check strings on crowdin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew clean checkStringResources --no-daemon

      - name: Checkout main branch for merge
        uses: actions/checkout@v7
        with:
          ref: main
          fetch-depth: 0
          clean: true

      - name: Fetch crowdin branch
        run: git fetch origin crowdin

      - name: Squash merge crowdin into main
        run: |
          git config --local user.name "Crowdin Bot"
          git config --local user.email "support+bot@crowdin.com"
          git merge --squash origin/crowdin
          git commit --allow-empty -m "chore: Update translations from Crowdin"
          git push origin main
